apiVersion: v2
name: falco
description: Umbrella chart — wraps falcosecurity/falco (includes falcosidekick)
type: application
version: 1.0.0
dependencies:
  - name: falco
    version: 4.8.0
    repository: https://falcosecurity.github.io/charts
